sudo: required
language: node_js
node_js:
- '4.2'
before_script:
- npm install
- npm i -g typescript typings
- typings install
- tsc

script: npm run tsc
before_deploy:
- mkdir -p dpl_cd_upload
- mv sfssffsf dpl_cd_upload/sfssffsf
