version: 0.0
os: windows
files:
  - source: /tsconfig.json
    destination: /home/ts.js
  - source: app
    destination: /home/Jetty/demo-base/webapps/ROOT/myApp
hooks:
  BeforeInstall:
    - location: /scripts/stop-server.bat
  AfterInstall:
    - location: /scripts/start-server.bat
