version: 0.0
os: windows
files:
  - source: /tsconfig.json
    destination: /home
  - source: /demo-webapp-root
    destination: /home/Jetty/demo-base/webapps/ROOT
hooks:
  BeforeInstall:
    - location: /scripts/before-deploy.bat
  AfterInstall:
    - location: /scripts/after-deploy.bat
    
